Bug/ai 85 show info language fix
Sundsvallskommun/web-app-interpreter pull request #5
Opened 2024-11-11 15:01 UTC by alicefagerbergsk

…ranslation and common on recording box info text and button

## Types of changes

- [x] Bug fix
- [ ] New feature
- [ ] Removed feature
- [ ] Code style update (formatting etc.)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes

## Does this PR introduce a breaking change?
- [ ] Yes (I have stepped the version number accordingly)
- [x] No
      
## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly (if applicable).
- [ ] I have added/updated tests to cover my changes (if applicable).

2024-11-11 15:24 UTC, alicefagerbergsk commented
https://jira.sundsvall.se/browse/AI-85

2024-11-12 11:06 UTC, alicefagerbergsk commented
@jerkerosatiesk

2024-11-12 11:10 UTC, jerkerosatiesk requested changes

2024-11-12 11:10 UTC, jerkerosatiesk commented on src/views/Start.tsx
> +  const counterpartsLanguage = languages[2].split("-")[0];
Första sidan ska följa person as språk.
Varningsrutan ska följa person bs språk.

Förslag: Bryt ut varningsrutan till en egen komponent.

2024-11-12 12:32 UTC, alicefagerbergsk commented on src/views/Start.tsx
> +  const counterpartsLanguage = languages[2].split("-")[0];
ahh JAHA. I fix

2024-11-13 14:48 UTC, jerkerosatiesk approved these changes

2024-11-13 15:16 UTC, merged